apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          emptyDir: {}
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: rabbitmq
#spec:
#  selector:
#    app: rabbitmq
#  ports:
#    - name: amqp
#      protocol: TCP
#      port: 5672
#      targetPort: 5672
#    - name: management
#      protocol: TCP
#      port: 15672
#      targetPort: 15672
#  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clone-svc
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP