apiVersion: v1
kind: Service
metadata:
  name: vault-reader-svc
spec:
  type: ClusterIP
  selector:
    app: vault-reader-app
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
